[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "aiohttp",
    "asyncpg",
    "fastapi",
    "loguru",
    "pipecat-ai[cartesia,elevenlabs,google,openai,sarvam,silero,deepgram]",
    "pipecat-vobiz",
    "pypdf",
    "python-dotenv",
    "python-multipart",
    "qdrant-client",
    "uvicorn[standard]",
    "sentence-transformers",
    "num2words",
    "python-jose[cryptography]",
    "bcrypt",
]

[tool.uv]
prerelease = "allow"
